-- MySQL Script generated by MySQL Workbench
-- Thu May 19 14:12:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table administrator
-- -----------------------------------------------------
DROP TABLE IF EXISTS "administrator";
CREATE TABLE IF NOT EXISTS "administrator" (
"id" SERIAL PRIMARY KEY,
"username" VARCHAR(45) NOT NULL,
"password" VARCHAR(255) NOT NULL
);

-- -----------------------------------------------------
-- Table employee
-- -----------------------------------------------------
DROP TABLE IF EXISTS employee;
CREATE TABLE IF NOT EXISTS employee (
  "id" SERIAL PRIMARY KEY,
  "username" VARCHAR(45) NULL,
  "password" VARCHAR(255) NULL,
  "name" VARCHAR(255) NULL
);

-- -----------------------------------------------------
-- Table address
-- -----------------------------------------------------
DROP TABLE IF EXISTS "address";
CREATE TABLE IF NOT EXISTS "address" (
  "id" SERIAL PRIMARY KEY,
  "street" VARCHAR(100) NULL,
  "number" INT NULL,
  "district" VARCHAR(50) NULL,
  "city" VARCHAR(100) NULL,
  "state" VARCHAR(50) NULL,
  "country" VARCHAR(50) NULL
);

-- -----------------------------------------------------
-- Table customer
-- -----------------------------------------------------
DROP TABLE IF EXISTS "customer";
CREATE TABLE IF NOT EXISTS "customer" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "phone" VARCHAR(11) NULL,
  "cpf" VARCHAR(45) NOT NULL,
  "sex" CHAR(1) NOT NULL,
  "address_id" INT NOT NULL,
  CONSTRAINT fk_customer_address1
    FOREIGN KEY (address_id)
    REFERENCES "address" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- -----------------------------------------------------
-- Table order
-- -----------------------------------------------------
DROP TABLE IF EXISTS "order";
CREATE TABLE IF NOT EXISTS "order" (
  "id" SERIAL PRIMARY KEY,
  "customer_id" INT NOT NULL,
  "administrator_id" INT NOT NULL,
  "description" TEXT NULL,
  "name" VARCHAR(255) NOT NULL,
  "date_order" DATE NOT NULL,
  "date_deliver" DATE NOT NULL,
  "price" DECIMAL(6) NOT NULL,
  type VARCHAR(45) NOT NULL,
  CONSTRAINT fk_orders_customers
    FOREIGN KEY ("customer_id")
    REFERENCES customer ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_orders_administrator1
    FOREIGN KEY (administrator_id)
    REFERENCES "administrator" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- -----------------------------------------------------
-- Table alert
-- -----------------------------------------------------
DROP TABLE IF EXISTS "alert";
CREATE TABLE IF NOT EXISTS "alert" (
  "id" SERIAL PRIMARY KEY,
  "order_id" INT NOT NULL,
  "date" TIME NULL,
  "done" CHAR(1) NULL,
  CONSTRAINT fk_alert_orders1
    FOREIGN KEY (order_id)
    REFERENCES "order" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
